### PR TITLE
feat(event): add metadata attribute

### PR DESCRIPTION
**Pull request by jnelle**
* add metadata attribute to save additional informations

Signed-off-by: jnelle <jimmy@nelle.sh>

### CODE REVIEW

**Comment by jnelle** [comment]
Hi, I've added a metadata attribute that gives the possibility to add more data for an event

**Review by rwbr — COMMENTED** [review]
Not of much use at the moment. But ok.

**Review by rwbr — APPROVED** [review]

**Comment by jnelle** [comment]
I thought it's good especially if you want save some informations about a specific event. For example, I'm using it to save some user ids and the event id

```dart
extension MyScheduleConversion on Appointment {
  NeatCleanCalendarEvent convertToCalendarEvent(
          {required String name,
          required String trainerId,
          required String trainerName}) =>
      NeatCleanCalendarEvent(
        name,
        startTime: startTime!.toLocal(),
        endTime: endTime!.toLocal(),
        location: '${location!.street}, ${location!.city}',
        description: '$description mit $trainerName',
        color: ColorName.secondaryColor,
        metadata: <String, dynamic>{
          'id': id,
          'trainer_id': trainerId,
          'is_appointment': true,
          'invitor_id': invitorId,
        },
      );
}
```

**Comment by rwbr** [comment]
That's fine. I see your point. Makes sense. Thank's for contributing.

**Comment by jjvillavicencio** [comment]
Hola, el campo de metadatos no se conserva cuando el evento comienza y finaliza en un día diferente, porque en este caso el método _updateEventsMap crea una nueva clase sin campo de metadatos.

> I thought it's good especially if you want save some informations about a specific event. For example, I'm using it to save some user ids and the event id
> 
> ```dart
> extension MyScheduleConversion on Appointment {
>   NeatCleanCalendarEvent convertToCalendarEvent(
>           {required String name,
>           required String trainerId,
>           required String trainerName}) =>
>       NeatCleanCalendarEvent(
>         name,
>         startTime: startTime!.toLocal(),
>         endTime: endTime!.toLocal(),
>         location: '${location!.street}, ${location!.city}',
>         description: '$description mit $trainerName',
>         color: ColorName.secondaryColor,
>         metadata: <String, dynamic>{
>           'id': id,
>           'trainer_id': trainerId,
>           'is_appointment': true,
>           'invitor_id': invitorId,
>         },
>       );
> }
> ```

Hi, metadata field don't preserves when the event starts and ends on different day, because in this case the _updateEventsMap method create a new class without metadata field

**Comment by jjvillavicencio** [comment]
> I thought it's good especially if you want save some informations about a specific event. For example, I'm using it to save some user ids and the event id
> 
> ```dart
> extension MyScheduleConversion on Appointment {
>   NeatCleanCalendarEvent convertToCalendarEvent(
>           {required String name,
>           required String trainerId,
>           required String trainerName}) =>
>       NeatCleanCalendarEvent(
>         name,
>         startTime: startTime!.toLocal(),
>         endTime: endTime!.toLocal(),
>         location: '${location!.street}, ${location!.city}',
>         description: '$description mit $trainerName',
>         color: ColorName.secondaryColor,
>         metadata: <String, dynamic>{
>           'id': id,
>           'trainer_id': trainerId,
>           'is_appointment': true,
>           'invitor_id': invitorId,
>         },
>       );
> }
> ```

Hi, metadata field don't preserves when the event starts and ends on different day, because in this case the _updateEventsMap method create a new class without metadata field

**Comment by BuddhaCodes** [comment]
Any solution for the it?

**Comment by jnelle** [comment]
@rwbr I‘ll check it later

**Pull request merged**
