### PR TITLE
show events & events with icons

### PR DESCRIPTION
**Pull request by AyeshaIftikhar**
Hi there!
I hope you are doing great. Loved your package, really very easy to use and feasible but I found a few things that can be improved. So instead of causing you the trouble to add those things, I am generating a PR with those functions. I have implemented them in one of my projects using your package's local version and they do great so I thought they should be shared with others. 

Things I have added into the package:
- Ability to show & hide events
- Added the ability to add icons with events

Test multiple times and working properly, added the screenshots in the `img` folder as well to showcase the responses. 
I hope you guys find it useful and worth sharing with other.  Be sure to ping me in case of any queries.

Thanks & Regards,
Ayesha Iftikhar

### CODE REVIEW

**Comment by jnelle** [comment]
really beautiful, great work! :)

**Comment by AyeshaIftikhar** [comment]
Thanks

**Comment by rwbr** [comment]
I need to know, from which source you took the example pictures in the assets folder. This is because I don't need to come into conflict with copyright law.

**Comment by AyeshaIftikhar** [comment]
> I need to know, from which source you took the example pictures in the assets folder. This is because I don't need to come into conflict with copyright law.

I took those pictures from Pexels.com and these were the free stock photos.

**Pull request merged**
